name: build and publish

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: build jar
        run: ./gradlew --no-daemon build

      - name: build docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
